#!/bin/bash
#PBS -V
#PBS -N centrifuge-build
#PBS -l nodes=1:ppn=64
#PBS -l walltime=200:00:00

cd ~/nas3/meta/centrifuge
#head -500 /nas3/database/nt_fa/nt.fa

cat ../plants_genbank/final.fa ../plastids_refseq/final.fa > centref.fa
sed "s/|kraken:taxid|/ /" centref.fa > centref2.fa
rm centref.fa
centrifuge-build -p 64 --bmax 1619356040 --conversion-table ../acc2tid.map --taxonomy-tree ../taxonomy/nodes.dmp --name-table ../taxonomy/names.dmp ./centref2.fa ../centrifuge/allplants



#centrifuge -p 64 -q -x ~/nas3/meta/centrifuge/nt -U ../fastq/ERR1560012.fastq -S centclass --report-file cenrifuge_report.tab
